//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace algebra_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBoleta
    {
        public TBoleta()
        {
            this.TDetalle = new HashSet<TDetalle>();
        }
    
        public int NroBoleta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CodCliente { get; set; }
        public string CodVendedor { get; set; }
        public Nullable<bool> Anulado { get; set; }
    
        public virtual TCliente TCliente { get; set; }
        public virtual TVendedor TVendedor { get; set; }
        public virtual ICollection<TDetalle> TDetalle { get; set; }
    }
}
