//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace algebra_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCategoria
    {
        public TCategoria()
        {
            this.TCategoria1 = new HashSet<TCategoria>();
            this.TProducto = new HashSet<TProducto>();
        }
    
        public string CodCategoria { get; set; }
        public string Nombre { get; set; }
        public string CategoriaPadre { get; set; }
    
        public virtual ICollection<TCategoria> TCategoria1 { get; set; }
        public virtual TCategoria TCategoria2 { get; set; }
        public virtual ICollection<TProducto> TProducto { get; set; }
    }
}
