//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace algebra_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDetalle
    {
        public int NroBoleta { get; set; }
        public string CodProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
    
        public virtual TBoleta TBoleta { get; set; }
        public virtual TProducto TProducto { get; set; }
    }
}
