//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace algebra_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProducto
    {
        public TProducto()
        {
            this.TDetalle = new HashSet<TDetalle>();
        }
    
        public string CodProduto { get; set; }
        public string Nombre { get; set; }
        public string UnidadDeMedida { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Stock { get; set; }
        public string CodCategoria { get; set; }
    
        public virtual TCategoria TCategoria { get; set; }
        public virtual ICollection<TDetalle> TDetalle { get; set; }
    }
}
