//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace algebra_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVendedor
    {
        public TVendedor()
        {
            this.TBoleta = new HashSet<TBoleta>();
        }
    
        public string CodVendedor { get; set; }
        public string Apellidos { get; set; }
        public string Nombres { get; set; }
    
        public virtual ICollection<TBoleta> TBoleta { get; set; }
    }
}
