//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace algebra_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDVentasEntities : DbContext
    {
        public BDVentasEntities()
            : base("name=BDVentasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBoleta> TBoleta { get; set; }
        public DbSet<TCategoria> TCategoria { get; set; }
        public DbSet<TCliente> TCliente { get; set; }
        public DbSet<TDetalle> TDetalle { get; set; }
        public DbSet<TProducto> TProducto { get; set; }
        public DbSet<TVendedor> TVendedor { get; set; }
    }
}
