//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algebra_2
{


    public partial class WebForm2
    {

        /// <summary>
        /// Control form1.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Control btnConsulta1.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta1;

        /// <summary>
        /// Control btnConsulta2.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta2;

        /// <summary>
        /// Control btnConsulta3.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta3;

        /// <summary>
        /// Control btnConsulta4.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta4;

        /// <summary>
        /// Control btnConsulta5.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta5;

        /// <summary>
        /// Control btnConsulta6.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta6;

        /// <summary>
        /// Control btnConsulta7.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta7;

        /// <summary>
        /// Control btnConsulta8.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta8;

        /// <summary>
        /// Control btnConsulta9.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta9;

        /// <summary>
        /// Control btnConsulta10.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta10;

        /// <summary>
        /// Control btnConsulta11.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta11;

        /// <summary>
        /// Control btnConsulta12.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta12;

        /// <summary>
        /// Control btnConsulta13.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta13;

        /// <summary>
        /// Control btnConsulta14.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta14;

        /// <summary>
        /// Control btnConsulta15.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta15;

        /// <summary>
        /// Control btnConsulta16.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta16;

        /// <summary>
        /// Control btnConsulta17.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta17;

        /// <summary>
        /// Control btnConsulta18.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConsulta18;

        /// <summary>
        /// Control gvConsulta.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvConsulta;
    }
}